apiVersion: v1
kind: Service
metadata:
  name: final-project
spec:
  selector:
    app: final-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: LoadBalancer