apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
        - name: final-project
          image: final-project:2025
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi